version: '3.8'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - '9000:9000'
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresqlserverdevelop.postgres.database.azure.com:5432/sonarqube?sslmode=require
      SONAR_JDBC_USERNAME: postgresql
      SONAR_JDBC_PASSWORD: Gelo+123
      SONAR_JDBC_MAXACTIVE: 5
      SONAR_JDBC_MAXIDLE: 2
      SONAR_JDBC_MINIDLE: 1
      SONAR_JDBC_MAXWAIT: 5000

    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    #restart: unless-stopped

volumes:
  sonarqube_data: null
  sonarqube_extensions: null
  sonarqube_logs: null