name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Azure VM
      env:
        AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
        AZURE_VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
        AZURE_VM_SSH_KEY: ${{ secrets.AZURE_VM_SSH_KEY }}
      run: |
        scp -o StrictHostKeyChecking=no -i $AZURE_VM_SSH_KEY -r . $AZURE_VM_USERNAME@$AZURE_VM_IP:~/app
        ssh -o StrictHostKeyChecking=no -i $AZURE_VM_SSH_KEY $AZURE_VM_USERNAME@$AZURE_VM_IP << 'EOF'
          cd ~/app
          docker build -t sonarqube:latest .
          docker stop sonarqube || true
          docker rm sonarqube || true
          docker run -d --name sonarqube -p 9000:9000 --restart unless-stopped sonarqube:latest
        EOF
