name: Deploy to Azure VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "${{ secrets.AZURE_VM_SSH_KEY }}" > azure_vm_ssh_key
        chmod 600 azure_vm_ssh_key
        ls -l azure_vm_ssh_key  # Check if the file is created and has the correct permissions
      
    - name: Deploy to Azure VM
      env:
        AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
        AZURE_VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
        AZURE_VM_SSH_KEY: ${{ secrets.AZURE_VM_SSH_KEY }}
        SONAR_JDBC_URL: ${{ secrets.SONAR_JDBC_URL }}
        SONAR_JDBC_USERNAME: ${{ secrets.SONAR_JDBC_USERNAME }}
        SONAR_JDBC_PASSWORD: ${{ secrets.SONAR_JDBC_PASSWORD }}
      run: |
        scp -o StrictHostKeyChecking=no -i azure_vm_ssh_key -r ./ $AZURE_VM_USERNAME@$AZURE_VM_IP:/home/azureuser/
        ssh -o StrictHostKeyChecking=no -i azure_vm_ssh_key $AZURE_VM_USERNAME@$AZURE_VM_IP << 'EOF'
          cd /home/azureuser/
          docker build -t sonarqube:latest .
          docker stop sonarqube || true
          docker rm sonarqube || true
          docker run -d --name sonarqube \
            -p 9000:9000 \
            -e SONAR_JDBC_URL=$SONAR_JDBC_URL \
            -e SONAR_JDBC_USERNAME=$SONAR_JDBC_USERNAME \
            -e SONAR_JDBC_PASSWORD=$SONAR_JDBC_PASSWORD \
            --restart unless-stopped sonarqube:latest
        EOF
